// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://crphxcbvdzuqfuwvczkh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNycGh4Y2J2ZHp1cWZ1d3ZjemtoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA2MTU1MjgsImV4cCI6MjA3NjE5MTUyOH0.Iv5umLgXt67P55ErzlhryPXGWEvDPKTGITEqeTdSAjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);